#!/usr/bin/env python3
"""Generate the Flux dependsOn graph as Mermaid, from kubernetes/apps/**/ks.yaml.

The README's dependency diagram is this script's output, between the
<!-- depgraph:start --> and <!-- depgraph:end --> markers. Don't edit it by
hand: change the ks.yaml files and re-run with --write.

  (no args)        print the Mermaid block
  --write FILE     replace the block between the markers in FILE
  --check FILE     exit 1 (with a diff) if FILE's block is out of date

Always fails if a dependsOn names a Kustomization that does not exist.
"""
import difflib
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
APPS = ROOT / "kubernetes" / "apps"
START, END = "<!-- depgraph:start -->", "<!-- depgraph:end -->"


def load():
    """{name: (group, [dependsOn names])}, group = the kubernetes/apps/<dir>."""
    nodes = {}
    for ks in sorted(APPS.glob("*/*/ks.yaml")):
        group = ks.relative_to(APPS).parts[0]
        for doc in yaml.safe_load_all(ks.read_text()):
            if not doc or doc.get("kind") != "Kustomization":
                continue
            deps = [d["name"] for d in doc["spec"].get("dependsOn", [])]
            nodes[doc["metadata"]["name"]] = (group, deps)
    return nodes


def node_id(name: str) -> str:
    return re.sub(r"\W", "_", name)


def render(nodes) -> str:
    missing = sorted({d for _, deps in nodes.values() for d in deps} - nodes.keys())
    if missing:
        sys.exit(f"dependsOn names unknown Kustomization(s): {', '.join(missing)}")
    lines = ["```mermaid", "flowchart LR"]
    for group in sorted({g for g, _ in nodes.values()}):
        lines.append(f'  subgraph {node_id("ns_" + group)}["{group}"]')
        for name in sorted(n for n, (g, _) in nodes.items() if g == group):
            lines.append(f'    {node_id(name)}["{name}"]')
        lines.append("  end")
    for name in sorted(nodes):
        for dep in sorted(nodes[name][1]):
            lines.append(f"  {node_id(dep)} --> {node_id(name)}")
    lines.append("```")
    return "\n".join(lines)


def block(nodes) -> str:
    return "\n".join([
        START,
        "<!-- Generated by .github/scripts/depgraph.py --write README.md; "
        "edit the ks.yaml files, not this block. -->",
        render(nodes),
        END,
    ])


def split(text: str, path: str):
    try:
        a = text.index(START)
        b = text.index(END) + len(END)
    except ValueError:
        sys.exit(f"{path}: missing {START} / {END} markers")
    return text[:a], text[a:b], text[b:]


def main(argv) -> int:
    nodes = load()
    if not argv:
        print(render(nodes))
        return 0
    if len(argv) != 2 or argv[0] not in ("--write", "--check"):
        print(__doc__, file=sys.stderr)
        return 64
    path = Path(argv[1])
    before, current, after = split(path.read_text(), argv[1])
    wanted = block(nodes)
    if argv[0] == "--write":
        path.write_text(before + wanted + after)
        return 0
    if current == wanted:
        return 0
    sys.stdout.writelines(difflib.unified_diff(
        (current + "\n").splitlines(True), (wanted + "\n").splitlines(True),
        f"{argv[1]} (committed)", "generated from ks.yaml"))
    print(f"\n{argv[1]}: dependency graph is stale. "
          f"Run: python3 .github/scripts/depgraph.py --write {argv[1]}")
    return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
