apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: sunfire
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:zmtTBGL5gUDhMpUkSZiNlsrVE9z3aowFZuOxzDxYe/7f3V7tNQIJCBjzg0XRWYvS+LFVXvhlZGs1k9ADa+O/LclyO4AMqEC0sorlJ5/Ss0hRiIC3E2leGCcwuxYmtFslAL59BfkbAP1c8kGqhF8wBIYWavbL2EXwMaGZBbSefmMjWxgMGqUEgId9adO/PW0vz03PPM+8klmaKY4qwenNLOB9mw+h,iv:dj4b5H7yPwYVoVEKSdYT1IuzMotuVYpJkDR3grr7/Ak=,tag:3lCb18/kH2wVzQvkaD8w3w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBic0tDZkc0T3htVHFZcG1E
            V3hzazRXNktqN1QwWklDMmphTDNxU0cvZmlNCmhyZWdHSmh6clRGemN3VWxlbG5N
            cjREdUtvc3lpdDM1U1Ayb002NFczYXMKLS0tIDFIN2plT3o1VTluSWdzdC92V1g0
            ejdPQjcxNGNzdkR3NVk4Znp5VzlrcUEKsqYf51gVB3bt9lQKgILo+mzfCEvDJCww
            QaNXvpyRwM1kAa94dQBrtCcu8qWKz+ukQ9PKfowFduCAgKaAVF7wGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ncpf5hg778lpszpv0u9mm48k5sdlm4y4v4dfsnaqskuwtwfgn3eqkz25qt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-04T03:54:31Z"
    mac: ENC[AES256_GCM,data:3DezNEryoPE3mnuKuaHS4N7J8y+aJ8Nha3L8cN1OzGkWW6q+fdtOmP96hU7fiOkuvcgB3JS2D+g0QJp/9a4sAD8LgWgNltC7iRH49c5uUrdmw43l9biEfGTqgoqq5pRZVsBGTkhqVsMOmzLDnSJAlRGDaSsN7/Nh0QQKVaK4YcE=,iv:SdRZltfbPhfyIXSywqs/UCoD63azr+M8emo6vBOfXhM=,tag:feiUNJhG+AMh+/nM3Jvszg==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
