apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: sunfire
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:GN1GcpUiOrDnHWlUhO3bYzEI0iuqD/Q1Zwh8mv78UMl9nYf43ga3YW6AFkhkx2RARDtd6tkfTGAuptJIbhLYyV6rU+qGY+xkmncbQ8T+0Dqy03PgqpcBTkC0pkUqXPbdN1FAo+gB/f1ziynioBy5MoXAl2ZqNcuzNtl+jOtw59zSuH4Cy8ndql55/3osu4P61rx6ljsy5WiSBIvxWobEeV4=,iv:+/Zywu3q5ve4PtwFs+xxHaLtQeIo8TVfvNblTt3CGsk=,tag:8arPq9XSPe/F8kH23loaNg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtbDZCbW5pVkRUTk9YK2hL
            RXhGVTFPM09FUWdGUnJFR1kxSnMrUkhwdEZRCjNqVTc4elFjcFphN2prMDZ4aHFj
            RlZIdnhXQkVLZlY3bS96Y3g2MUpTL3cKLS0tIFVBRDdabll6cnhHNjdQczVNaENS
            L3RYSFVpTzV0NVp6NlNIR2sxMEtxc00Kym0C7dkajPD0HDrI6V/k3NoNxrKKQA4I
            3ognJvk160sTygPL51d1mL6ZQhqAjgovwHQydjfFlaDKj7Nks6f/1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ncpf5hg778lpszpv0u9mm48k5sdlm4y4v4dfsnaqskuwtwfgn3eqkz25qt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-04T05:59:46Z"
    mac: ENC[AES256_GCM,data:IIJWUw8/b4Ydu5DE1OYfty+ZQP7+8DPvs9Dn8d9NSB07rphQ3UcJJTxusoxk9ad8ze3bOTCg93aVFPZGYpXWgbcQzFMGakuMa1B7eoTxbYZssJHDkiYMie3XbmCZQvpa13UwvcoZNFlO/hp+jjUr8mdu10iilVgw8ODUhDlj4Zo=,iv:6PBxXgc6eQ7QxxRC7lvYPo0mLsEOH+OOtM77yImI9QM=,tag:KA1Lm7fBDM0Io41AuKZqYA==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
