apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: sunfire
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:zNyCIhG6iEoLWlFTV6LjysdgNgtTYMTkQi1MwLZIfKNl8v+ctTL/hU3WNkxU3TSWwteFSlFEY4Thp69934H3PEEzl/8NU7u86t4zNOGQnJrI1kH5On/ZxSVxqwSWP9+PHKDuBfMhTr+CSwAee56lfZfsntmGUhTTVorAAV/d5MxfLdb0Lrw0D0d+n6BBEYf3km6M4KnRFZdqW4fqumRs5iZFtTpA6UKZmaZ77XhDp+poNm7BlbG2nA==,iv:YxaXR2W1r7+VdgaAmenk+xgH9he6SRIzPhg+MirU7g8=,tag:qxe1iuDeoNrfYCSqmtR0/w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxOTZLN1lrUlFITjFjamxH
            bEdFT085RkRxTlZIWk02bHJUWTJndUNtU244CkRjZjV1MnRmV21ObnhRU3FTMnVj
            aVJFZlNIVUoySHltVU5EbnBpWktJMGMKLS0tIDdSdjdXMk9BU1V5cVdwaHE4c3R2
            aUw4dUFZV09xcFF1TmZ4KzBFV1pqREUKBfWYQUhL0iG3lKjCX7VQaxsqEPXjXx5V
            w9m00Lqz/ImP5LNxSOfgqZRnBjvGyDav9LqR2x5DyBGLic82JPopmw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ncpf5hg778lpszpv0u9mm48k5sdlm4y4v4dfsnaqskuwtwfgn3eqkz25qt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-02T22:11:15Z"
    mac: ENC[AES256_GCM,data:B+NdrACISPpsb6BG1XE2VWeHVAnsLDCHm3OkGc3subcwyjJkStnUAz01NEE6rtD077VjhScD9A8Z61qTJYPz20b8GdAEwnYnTObcaQtwhaxZajaz1w5o/6GcY6DEZ5ZnD6ag9VojEu+t4ImNRWHVndctRbj4TY5t4vygOeyIgyo=,iv:UsldvilGlY5u9VIDB+xWhWari3D1aEYi4Cm6GLAoiEQ=,tag:/+1xutf7KyRc9Z9K30mRGw==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
