apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: sunfire
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:JYiKt9dGt2px11f7Za7N2rFQhpT2iqaJPwZ/LAo4zhDytzaCJVKP9Pf3oiEgyMFCVC82T3FfAbyRr7ceN6p7DZEl7endaLTwdJv1vsP0RkhuzAdex7ovuWWWxE4+rShM6LBflm1J5Y1eEl7aBJ4m+ekW6oqpuA2arJU/pumNm6icYUYDdvML7ccIQpb+mq9hr9qTjZ9pj2+knF2NUysshz6oVmP3Tke7f8KwvpfvLGFa2ywVYmiKQw==,iv:keNmlA4bf6HB5NshQ0kZNkRCRc1pbRHCvOzSqHnLXIY=,tag:m+tBa9lcb/vxu5UwyIywLg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxOTZLN1lrUlFITjFjamxH
            bEdFT085RkRxTlZIWk02bHJUWTJndUNtU244CkRjZjV1MnRmV21ObnhRU3FTMnVj
            aVJFZlNIVUoySHltVU5EbnBpWktJMGMKLS0tIDdSdjdXMk9BU1V5cVdwaHE4c3R2
            aUw4dUFZV09xcFF1TmZ4KzBFV1pqREUKBfWYQUhL0iG3lKjCX7VQaxsqEPXjXx5V
            w9m00Lqz/ImP5LNxSOfgqZRnBjvGyDav9LqR2x5DyBGLic82JPopmw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ncpf5hg778lpszpv0u9mm48k5sdlm4y4v4dfsnaqskuwtwfgn3eqkz25qt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-03T04:05:04Z"
    mac: ENC[AES256_GCM,data:+HBEJlrQlaUQ7swBk/BYzircgBVuzStNe1iNQH5DiuLs6FnruzMRvseL7gOPaJ8n6W99pVtpAo+bxMrMblmJOLQTZBgbMKdR8MLC7n75xDr5STgftOaFJI7smRZnmHiyeeLLV8RQ+8d2EPlm5NokcWMjdzKnhcZ67ALLqMA2Bm0=,iv:FI2awmriK0KW4FGFPsELHvUg6Ch+EycECMsKzxH+qLo=,tag:nbfJCuER7wMtHOOIBxSJag==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
