apiVersion: v1
kind: Secret
metadata:
    name: postgrest-config
    namespace: sunfire
type: Opaque
stringData:
    PGRST_DB_URI: ENC[AES256_GCM,data:mrUKv9q4gxccA/bkXy+prJKG+58AIKOfjqm7gXgrLreS91Xsfr4/VdwJdlmJ3Qch3g+5VRiEUpUBJTZhs5LkvfYtSfwa3+tSnUoPG+2iX01YcKvYKqL7U4sSYKbwinG7j0SnjlPAJ4wEjnGydUlJEviogwVdH640hS5lFDJjuRSy,iv:RkKLBaO9e73u8hI/QZypRVwN2y9BmiUo2ncpI8c2PFw=,tag:7Ykj+5fd7kzJHl+ljllGlg==,type:str]
    PGRST_JWT_SECRET: ENC[AES256_GCM,data:7vsIvdMa2+fnO1/usr1T3UgbnVS1HL0cA4Ceq15yVG6MwvRkVPomLlL5H4u2vtS0Oys2goXOHXWMcScCJhAsuA==,iv:i8MLjcbC/utNa1RCEjZTbhVanu807DUac+jwL9dQyXQ=,tag:LBRlyEbeHEKw4TmJsoW51A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2QWpHUEZyaTJaZGNFeUpU
            dGt2dHhOaGZnQ2NrOTFwY3dabFQyekMyd204Cmgvd203dlVzMlJwQmRzQVRsY09h
            MGcvMk1GVnVST0hTWFowRUNaaTlzUncKLS0tIDNNeGptb0grQUNyWHAxejFocjV4
            NUlxTGMrNGlFa3diUWYrRldZS2JDaEkKdLMPaereg9ahKfBXFa1SBr3BMLcssnef
            EswawxKl606nu1u4ncyTnuwsCxez9LaA6a5mAn5Ut7FjHm55ZZDEqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ncpf5hg778lpszpv0u9mm48k5sdlm4y4v4dfsnaqskuwtwfgn3eqkz25qt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-04T01:10:59Z"
    mac: ENC[AES256_GCM,data:imRIbPZHZopVwqgZpKoOjoet+q2T2EfjY+0CVl6y7PsqBRYLZWrCeLxnYLBsQNCSlb6IjGWDZuqUIkUXEMfqyXub9u+402xfZBM0oFEf5jG6l1eaXJN89ET0WvqOcdPotIpb7c98Ri8JUXU0MRJrPMBWYKHkJE84pE3o8ZJDvAw=,iv:diO+vYTJGh85qAH7VFb3oSzEK07GtyR2UhQr/j7h8bo=,tag:ooGwINMYX6z2KlBFZpXe+Q==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
