apiVersion: v1
kind: Secret
metadata:
    name: postgrest-config
    namespace: sunfire
type: Opaque
stringData:
    PGRST_DB_URI: ENC[AES256_GCM,data:mrUKv9q4gxccA/bkXy+prJKG+58AIKOfjqm7gXgrLreS91Xsfr4/VdwJdlmJ3Qch3g+5VRiEUpUBJTZhs5LkvfYtSfwa3+tSnUoPG+2iX01YcKvYKqL7U4sSYKbwinG7j0SnjlPAJ4wEjnGydUlJEviogwVdH640hS5lFDJjuRSy,iv:RkKLBaO9e73u8hI/QZypRVwN2y9BmiUo2ncpI8c2PFw=,tag:7Ykj+5fd7kzJHl+ljllGlg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2QWpHUEZyaTJaZGNFeUpU
            dGt2dHhOaGZnQ2NrOTFwY3dabFQyekMyd204Cmgvd203dlVzMlJwQmRzQVRsY09h
            MGcvMk1GVnVST0hTWFowRUNaaTlzUncKLS0tIDNNeGptb0grQUNyWHAxejFocjV4
            NUlxTGMrNGlFa3diUWYrRldZS2JDaEkKdLMPaereg9ahKfBXFa1SBr3BMLcssnef
            EswawxKl606nu1u4ncyTnuwsCxez9LaA6a5mAn5Ut7FjHm55ZZDEqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ncpf5hg778lpszpv0u9mm48k5sdlm4y4v4dfsnaqskuwtwfgn3eqkz25qt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-04T09:16:51Z"
    mac: ENC[AES256_GCM,data:mq1IaKUwGtidgnwzb95+DA/ZCh9laTZ9i8/KCkCBsnhqW/eaFumeNdb3SuqekpQyQ6Evdm7w4FuWgQPGlJgNlpnGhXwcORODIapSracF6Y6T2ngzsiE8yQLMor7zYWnqiH32KpIg1azAqeq6qQf48loQgmJ3GEAHmVO8aLSVcTU=,iv:vszbS7Z6BrGYW6/XYsWEMkldJptwxByBj6Etrn8n8iM=,tag:NYOyNL2McYL/0HfDZH8nug==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
