apiVersion: v1
kind: Secret
metadata:
    name: postgrest-config
    namespace: sunfire
type: Opaque
stringData:
    PGRST_DB_URI: ENC[AES256_GCM,data:XiEedu8t5+xsMHMwy5r+mwoorteZ9YM37pY/vepXrC69iLzM7imZoYSe5cMzk482DeNMGiq2iiIPPhYUDRyIkLhIR/vqnyrADuEzjQGd9x60/enoh9Cnj51j0JBZ78xZmL6GlrenaZ+hxYe13+6Dvm6alqyBcZFDWQ==,iv:UWJ+oCaaa9uzaIFnwf6ANvZqUwA9rH9ahIqCfwLakuQ=,tag:PDW+0UKmI6qyJh74U/3hZA==,type:str]
    PGRST_JWT_SECRET: ENC[AES256_GCM,data:7vsIvdMa2+fnO1/usr1T3UgbnVS1HL0cA4Ceq15yVG6MwvRkVPomLlL5H4u2vtS0Oys2goXOHXWMcScCJhAsuA==,iv:i8MLjcbC/utNa1RCEjZTbhVanu807DUac+jwL9dQyXQ=,tag:LBRlyEbeHEKw4TmJsoW51A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2QWpHUEZyaTJaZGNFeUpU
            dGt2dHhOaGZnQ2NrOTFwY3dabFQyekMyd204Cmgvd203dlVzMlJwQmRzQVRsY09h
            MGcvMk1GVnVST0hTWFowRUNaaTlzUncKLS0tIDNNeGptb0grQUNyWHAxejFocjV4
            NUlxTGMrNGlFa3diUWYrRldZS2JDaEkKdLMPaereg9ahKfBXFa1SBr3BMLcssnef
            EswawxKl606nu1u4ncyTnuwsCxez9LaA6a5mAn5Ut7FjHm55ZZDEqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ncpf5hg778lpszpv0u9mm48k5sdlm4y4v4dfsnaqskuwtwfgn3eqkz25qt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-02T22:11:15Z"
    mac: ENC[AES256_GCM,data:qqb1No/SjH+Knvmvw/LhatRw1n7AJZZqCLe2oQa+METfgUXWKrZFzZvlu/rL6Sp0ae45ect77rjdcgNOiI0l8M36Ka4KCgxyaI1l/FafDQzpkfEGzq3osGgv9PtkmxrPyztZfZ76m4jBTxntkkjXez1JXBO2lmRTvIKzzhQ8RZ0=,iv:4BRey2FUZXHKhKubSY3/CWoy7MropTYhYWfbb85de5k=,tag:2Vd+wvdaeBl5HtwHLWDflg==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
