apiVersion: v1
kind: Secret
metadata:
    name: searxng
    namespace: search
type: Opaque
stringData:
    SEARXNG_SECRET: ENC[AES256_GCM,data:/fJGLa/uPOEnEw4Vv1FrIgguWZu0hwFbKmi9uT1B+IJ1RMHLJX2OF4M9IFFj/Bz9yh8+JgYXY5zVLp2KwWvYig==,iv:iiPyJDb7S/c+wdoekY+/X1Uzh0FIM92p4OXuGYUkEeI=,tag:xumjA/bf2ttzzQg7y8C+Fw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMWRwRXc5Zm5UZGswcGx0
            ZEQyNHI2RG9ubkNnU1d0MTlWWTc2Mms4SGxnCmRVbE1PbUc0cm84eU5NeE5LeFFm
            QllIK2lXNHVkandSektOa2Uya2tnakUKLS0tIGwwbXFhc0Q3SEFmYm12MGljRjNS
            RHJJMjV1SHI1Z1N3Sy9LelU3T3dDNzAKNP4ZQFvXHDusrRP1C1O1mSzEe0CfS7tK
            pAi/tFvas3JGKCPGNQGVom3nq2ZzRvncgTOAW1EZ3CwkzVJ8Q0Vz+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ncpf5hg778lpszpv0u9mm48k5sdlm4y4v4dfsnaqskuwtwfgn3eqkz25qt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T17:36:33Z"
    mac: ENC[AES256_GCM,data:5ypnowCfkzI4Q1u3jTcTQ4qfS2ZxcJac+KK7Zv4cDuCFZLDMHweOXstg040OE5r/AvOFOanBig0NNavPI8AF+4hhxNGztBwFvugu2EBjkJ7tFtqxpFidmzwM2JtB+GekAK9zSUIMqqbdyXtHzMPsbCB3PXNVjJLlcCNlM4XMwkw=,iv:smLCyySJmxSDvxm9FCxJbNkmwd4uu50FyFyCNaWpsBo=,tag:qQ8JNjNkzCeb6vkx03THQw==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
