apiVersion: v1
kind: Secret
metadata:
    name: postgres-credentials
    namespace: sunfire
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:tX6pztnFW4cmrgWNHIsC6A21LUnNkrF+R+daqBENvpqMholLkodgzfIbOUF4novH,iv:rUXc0hRThZmOnIKIrSw3KDfve0rhYxQd/TWKxFDZqzo=,tag:GTyyuDdOcX0haq4RtCIUUQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSlVpcTVjZHgxS3U3eGJz
            UkdoZUVDenkwZDR5TUNZYkJWNFJ5WGxLTmlRClUrQURhSjVaWkMrTVVVYXVIbkcr
            dU1CSEhYb1lJSE9Mck9lZnlGaHI5YjAKLS0tIHdtR2pPNEc1Q083UWhRT3RpT3gy
            dDZmYTdsb0xzdHhsanpReTVpTGtYdlkK+b9oTI0PKjRrnemUae6WhBFk4XIR1CGK
            ozT/xA6tz8ulYM+TdUPnBMD9IF6tyVSU22vaePF+ORC+hApiyvZyHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ncpf5hg778lpszpv0u9mm48k5sdlm4y4v4dfsnaqskuwtwfgn3eqkz25qt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-02T22:11:15Z"
    mac: ENC[AES256_GCM,data:iF9DNLNOj6lChBdLJIBG6MvUUOa+gbYx1DdgXApO+KMPz++VzbCFVZgfWPEOms9IPeDDqJ7PJNLSWjnLndxd75AZvMI30pI8EjCVzbF/T/hHzs4F8Przp/7uNyej9idaECwnVM9UnzYhv9q3Q4UsXJFxIiZCPHKtti7scZwHBtM=,iv:MFfUrGe9gOe6SyRjz6g1P7LOXcASece9y1FQ2sVqRJw=,tag:+cTl11yJEKVAQOcXoAScJA==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
