apiVersion: v1
kind: Secret
metadata:
    name: infisical-machine-identity
    namespace: sunfire
type: Opaque
stringData:
    clientId: ENC[AES256_GCM,data:K/17cXyZ1Vl8Pb7rfj4tcB90O7jO14+Oka3fcUlYtfpHOrXs,iv:MwpYrprvUWg9RG9Che8vHDEWT5bUw78Jk2I4Gwbjt8s=,tag:ThCyi6hnWVAyvEdmlQUsZw==,type:str]
    clientSecret: ENC[AES256_GCM,data:yxu0SHxpclhOjaNxDXXeUyIozR5mxKi38ZtTHqaf93e6xQ624jte0bX6WxqCfppty1yAiLhqDMX4i0hhHjTcuA==,iv:+eHuoDYhOfAbeX4vpNgKrpa1eGp9PsXQ3CluJuFOjjE=,tag:Uthjo5QfYCRyKttzvZFRzQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUUp6alV5SEh5Vkx1WUhK
            ZEo1SldrNkNpVnlVNlJ0SFhsRmRCWUxtUjNVCkUzQURlZXhnZml1UkdJeWx4WnYx
            aGdGYm9BWVJXVUVsNllGZ3owRGFpVDAKLS0tIGJLeDdIMmxWdFlVbEVGRGdPR3Yz
            UUI2WGpBSzZSMlN5MmUrZUlVQmY5cVEKuMRKxHkwrDPaQpL9u9SEwvLoHot8LACE
            4m7XrofgNQXmQ4Py9wXzyzyghUCcaljvVhAdssx86M1qb0tNkorV9g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ncpf5hg778lpszpv0u9mm48k5sdlm4y4v4dfsnaqskuwtwfgn3eqkz25qt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-04T09:11:05Z"
    mac: ENC[AES256_GCM,data:zQ0hTgm5Z/Nh7k7Zrm4YIt2BQbSlA6G25DXBK03fGM4vZkDpk05KMSgaRteEWpgqaBPqkHhWvg0OYy3qo80OVMaEpuwQiSCJsoX5H+7X9w7WUavAcW7Wn/zfYWxHvjoAOqhPomgLmi57u8eAByHp1Pc66PmoGiZhjTP8lavkQ0I=,iv:A9pT4OhwBEFslgLB85nPQTPrx6OOA0nMgfSg5C8L30U=,tag:AnP80hVxNRawLIgNMuBfwg==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
