apiVersion: v1
kind: Secret
metadata:
    name: llm-api-key
    namespace: observability
type: Opaque
stringData:
    key: ENC[AES256_GCM,data:AMeTCNbzIT18Uk7QoM0XFMeUSUWkMSMGOhtImgBevQ9NaNiHrazYSs4pHhuCZGGhQiiXDsY9/a43h4kUJIEPPA==,iv:ZUihZQJFjXMzfrpi3O1UICorzDg2BHhuygrfyAO/eFE=,tag:fQm+85Loy2q87Lt52D492A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxVnFjdjVGbUZvWks1bWJL
            RDZtUWtaTm0vdzVMNVI1Nm8zdUdDNXdYR0JZCm50WXdjTjNocTdUajJPTjcxa2lh
            WkcwODQ3NEZUOExJQktOR1pLUlNVNTAKLS0tIGJhWnpFYk1JeThPSk0rOGpHQXZy
            NHNvbC9maktrejFTR0JxVXFHR29aTHMKOnzl2Fr5ZaxMgziJIiv2mSYNPvOFKbPx
            64UvLrsjzjJWcAoPxGhJ5foCbbMOJfBl86wQxImwcYgKIp/LhGjwDQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ncpf5hg778lpszpv0u9mm48k5sdlm4y4v4dfsnaqskuwtwfgn3eqkz25qt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T22:23:03Z"
    mac: ENC[AES256_GCM,data:c1baW72C60p9kFgvxPVafXyraWDPfKAa5BGqTGFcHdejRYnuPY4YjbidOwCpIA160LMRqZHttQ6RbtBnu6hUztzZ26koKOHEAkttCMZWrawbQdLZPiqJjjvpLlNeuQ06YDf5dLE2P3j9TRHzhm7UARppt7Ak97BGyP/qcf7+Zz4=,iv:FI1ohxlWNbxe5IqkCQBY+ryYJj0IuG2xdgN33eOk5HE=,tag:A4NSiA8gWAmJdz5FC0qAww==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
