# The four QEMU guests. Imported 2026-09-04: `4 to import, 0 to change,
# 0 to destroy`, which is the only acceptable result here -- an import that
# proposes changes means the config does not describe the machine, and on 104
# that machine holds the database.
#
# Bodies generated by `tofu plan -refresh=false -generate-config-out` from the
# live guests and then reviewed, never hand-written. Four attributes had to be
# deleted from the generated output, all of them empty or zero values emitted
# for unset optionals and then rejected by the provider's OWN validators:
#
#   affinity  = ""   -> "must contain numbers or number ranges separated by ','"
#   hugepages = ""   -> "expected hugepages to be one of [1024 2 any]"
#   units     = 0    -> "expected units to be in the range (1 - 262144)"
#   timeout_* = ...  -> client-side patience, not machine state (see the
#                       container file for why these produce a phantom diff)
#   mac_addresses    -> NOT a validator rejection: removed 2026-09-21. It is
#                       computed from the guest agent, and on a k3s node it
#                       lists every pod veth, so it is stale on the next pod
#                       restart. Once a refresh recorded the new ones, the
#                       plan tried to "restore" the import-day set.
#
# Generation and validation disagreeing is a provider bug, not a fact about the
# hypervisor. Deleting the attribute lets the schema default stand and the plan
# comes back clean.
#
# THE PRIVILEGE THIS COST. PVEAuditor cannot do this: bpg/proxmox re-resolves
# every volume through GET /nodes/pve/storage/{store}/content/{volume}, which
# PVE gates on VM.Config.Disk -- a WRITE privilege -- even though the same disk
# string is already readable in GET /nodes/pve/qemu/{id}/config. A TofuDisk role
# holding only VM.Config.Disk was stacked on PVEAuditor for the generation, then
# removed:
#
#   pveum role add TofuDisk --privs VM.Config.Disk
#   pveum acl modify / --users tofu@pve --roles PVEAuditor,TofuDisk
#   ... generate, review, import ...
#   pveum acl delete / --users tofu@pve --roles TofuDisk
#
# That was 2026-09-04. Since `!import` went `--privsep 1` (2026-09-16) the
# token needs the grant too; see tofu/README.md "The privilege that blocked
# the four VMs" for the current commands.
#
# Re-granting is only needed to regenerate a body. Ordinary `tofu plan
# -refresh=false` needs no Proxmox PRIVILEGES -- it makes no API call -- but it
# does still need PROXMOX_VE_API_TOKEN to be set to something, because the
# provider fails at configure time with "Unable to create Proxmox VE API
# credentials" before it ever decides whether to call anything.
#
# `prevent_destroy` is on all four deliberately. See the block in each resource.
#
# One warning is expected and cannot be fixed here: `network_device.enabled` is
# deprecated, and the provider's advice -- "remove the network_device block
# instead" -- does not apply, because these interfaces are enabled and real.
# Deleting just the attribute fails with "Incorrect attribute value type":
# network_device is a typed object list, so every attribute must be present.
# The warning stands until the provider drops the field.

import {
  to = proxmox_virtual_environment_vm.dev
  id = "pve/101" # 192.168.50.103 -- this dev VM, which holds this state file
}

import {
  to = proxmox_virtual_environment_vm.k3s_control
  id = "pve/102" # 192.168.50.104 -- control plane
}

import {
  to = proxmox_virtual_environment_vm.k3s_worker1
  id = "pve/103" # 192.168.50.105 -- minio
}

import {
  to = proxmox_virtual_environment_vm.k3s_worker2
  id = "pve/104" # 192.168.50.106 -- postgres; PGDATA zvol as archive-pool:vm-104-disk-0
}

resource "proxmox_virtual_environment_vm" "k3s_worker1" {
  # These are running machines, one of which holds the database and one of which
  # is the host of this state file. Nothing in this repo should ever be able to
  # replace them: an apply that proposes it is a bug in the config, and this
  # turns that bug into a refusal instead of an outage.
  lifecycle {
    prevent_destroy = true
  }
  acpi                                 = true
  bios                                 = "seabios"
  boot_order                           = ["scsi0", "ide2", "net0"]
  delete_unreferenced_disks_on_destroy = true
  description                          = ""
  hook_script_file_id                  = ""
  hotplug                              = null
  keyboard_layout                      = "en-us"
  kvm_arguments                        = ""
  machine                              = ""
  migrate                              = false
  name                                 = "k3s-worker1"
  network_device = [{
    bridge       = "vmbr0"
    disconnected = false
    enabled      = true
    firewall     = false
    mac_address  = "BC:24:11:35:4C:27"
    model        = "virtio"
    mtu          = 0
    queues       = 0
    rate_limit   = 0
    trunks       = ""
    vlan_id      = 0
  }]
  node_name           = "pve"
  on_boot             = false
  pool_id             = ""
  protection          = false
  purge_on_destroy    = true
  reboot              = false
  reboot_after_update = true
  scsi_hardware       = "virtio-scsi-single"
  started             = true
  stop_on_destroy     = false
  tablet_device       = true
  tags                = ["k3s"]
  template            = false
  vm_id               = 103
  agent {
    enabled = true
    timeout = "15m"
    trim    = false
    type    = "virtio"
  }
  cpu {
    architecture = ""
    cores        = 4
    flags        = []
    hotplugged   = 0
    limit        = 0
    numa         = false
    sockets      = 1
    type         = "x86-64-v2-AES"
  }
  disk {
    # 20 -> 32 on 2026-09-21 by hand (`qm resize 103 scsi0 +12G`): this token
    # cannot write to VM 103, so the file follows the host, not the reverse.
    # Worker1 holds the TSDB, Grafana, Alertmanager and Home Assistant's config
    # on its root disk and had ~2.4 GB left. See BACKLOG.md.
    aio               = "io_uring"
    backup            = true
    cache             = "none"
    datastore_id      = "local-lvm"
    discard           = "ignore"
    file_format       = "raw"
    file_id           = ""
    import_from       = ""
    interface         = "scsi0"
    iothread          = true
    path_in_datastore = "vm-103-disk-0"
    queues            = 0
    replicate         = true
    serial            = ""
    size              = 32
    ssd               = false
  }
  memory {
    dedicated      = 131072
    floating       = 0
    keep_hugepages = false
    shared         = 0
  }
  operating_system {
    type = "l26"
  }
}

# __generated__ by OpenTofu
resource "proxmox_virtual_environment_vm" "k3s_control" {
  # These are running machines, one of which holds the database and one of which
  # is the host of this state file. Nothing in this repo should ever be able to
  # replace them: an apply that proposes it is a bug in the config, and this
  # turns that bug into a refusal instead of an outage.
  lifecycle {
    prevent_destroy = true
  }
  acpi                                 = true
  bios                                 = "seabios"
  boot_order                           = ["scsi0", "ide2", "net0"]
  delete_unreferenced_disks_on_destroy = true
  description                          = ""
  hook_script_file_id                  = ""
  hotplug                              = null
  keyboard_layout                      = "en-us"
  kvm_arguments                        = ""
  machine                              = ""
  migrate                              = false
  name                                 = "k3s-control"
  network_device = [{
    bridge       = "vmbr0"
    disconnected = false
    enabled      = true
    firewall     = false
    mac_address  = "BC:24:11:FE:4B:4A"
    model        = "virtio"
    mtu          = 0
    queues       = 0
    rate_limit   = 0
    trunks       = ""
    vlan_id      = 0
  }]
  node_name           = "pve"
  on_boot             = false
  pool_id             = ""
  protection          = false
  purge_on_destroy    = true
  reboot              = false
  reboot_after_update = true
  scsi_hardware       = "virtio-scsi-single"
  started             = true
  stop_on_destroy     = false
  tablet_device       = true
  tags                = []
  template            = false
  vm_id               = 102
  agent {
    enabled = true
    timeout = "15m"
    trim    = false
    type    = "virtio"
  }
  cpu {
    architecture = ""
    cores        = 2
    flags        = []
    hotplugged   = 0
    limit        = 0
    numa         = false
    sockets      = 1
    type         = "x86-64-v2-AES"
  }
  disk {
    aio               = "io_uring"
    backup            = true
    cache             = "none"
    datastore_id      = "local-lvm"
    discard           = "ignore"
    file_format       = "raw"
    file_id           = ""
    import_from       = ""
    interface         = "scsi0"
    iothread          = true
    path_in_datastore = "vm-102-disk-0"
    queues            = 0
    replicate         = true
    serial            = ""
    size              = 15
    ssd               = false
  }
  memory {
    dedicated      = 8192
    floating       = 0
    keep_hugepages = false
    shared         = 0
  }
  operating_system {
    type = "l26"
  }
}

# __generated__ by OpenTofu
resource "proxmox_virtual_environment_vm" "dev" {
  # These are running machines, one of which holds the database and one of which
  # is the host of this state file. Nothing in this repo should ever be able to
  # replace them: an apply that proposes it is a bug in the config, and this
  # turns that bug into a refusal instead of an outage.
  lifecycle {
    prevent_destroy = true
  }
  acpi                                 = true
  bios                                 = "seabios"
  boot_order                           = ["scsi0", "ide2", "net0"]
  delete_unreferenced_disks_on_destroy = true
  description                          = ""
  hook_script_file_id                  = ""
  hotplug                              = null
  keyboard_layout                      = "en-us"
  kvm_arguments                        = ""
  machine                              = ""
  migrate                              = false
  name                                 = "dev"
  network_device = [{
    bridge       = "vmbr0"
    disconnected = false
    enabled      = true
    firewall     = false
    mac_address  = "BC:24:11:05:C0:79"
    model        = "virtio"
    mtu          = 0
    queues       = 0
    rate_limit   = 0
    trunks       = ""
    vlan_id      = 0
  }]
  node_name           = "pve"
  on_boot             = false
  pool_id             = ""
  protection          = false
  purge_on_destroy    = true
  reboot              = false
  reboot_after_update = true
  scsi_hardware       = "virtio-scsi-single"
  started             = true
  stop_on_destroy     = false
  tablet_device       = true
  tags                = []
  template            = false
  vm_id               = 101
  agent {
    enabled = true
    timeout = "15m"
    trim    = false
    type    = "virtio"
  }
  cpu {
    architecture = ""
    cores        = 4
    flags        = []
    hotplugged   = 0
    limit        = 0
    numa         = false
    sockets      = 1
    type         = "host"
  }
  disk {
    aio               = "io_uring"
    backup            = true
    cache             = "none"
    datastore_id      = "local-lvm"
    discard           = "ignore"
    file_format       = "raw"
    file_id           = ""
    import_from       = ""
    interface         = "scsi0"
    iothread          = true
    path_in_datastore = "vm-101-disk-0"
    queues            = 0
    replicate         = true
    serial            = ""
    size              = 32
    ssd               = false
  }
  memory {
    dedicated      = 32768
    floating       = 0
    keep_hugepages = false
    shared         = 0
  }
  operating_system {
    type = "l26"
  }
}

# __generated__ by OpenTofu
resource "proxmox_virtual_environment_vm" "k3s_worker2" {
  # These are running machines, one of which holds the database and one of which
  # is the host of this state file. Nothing in this repo should ever be able to
  # replace them: an apply that proposes it is a bug in the config, and this
  # turns that bug into a refusal instead of an outage.
  lifecycle {
    prevent_destroy = true
  }
  acpi                                 = true
  bios                                 = "seabios"
  boot_order                           = ["scsi0", "ide2", "net0"]
  delete_unreferenced_disks_on_destroy = true
  description                          = ""
  hook_script_file_id                  = ""
  hotplug                              = null
  keyboard_layout                      = "en-us"
  kvm_arguments                        = ""
  machine                              = ""
  migrate                              = false
  name                                 = "k3s-worker2"
  network_device = [{
    bridge       = "vmbr0"
    disconnected = false
    enabled      = true
    firewall     = false
    mac_address  = "BC:24:11:9E:50:5F"
    model        = "virtio"
    mtu          = 0
    queues       = 0
    rate_limit   = 0
    trunks       = ""
    vlan_id      = 0
  }]
  node_name           = "pve"
  on_boot             = false
  pool_id             = ""
  protection          = false
  purge_on_destroy    = true
  reboot              = false
  reboot_after_update = true
  scsi_hardware       = "virtio-scsi-single"
  started             = true
  stop_on_destroy     = false
  tablet_device       = true
  tags                = []
  template            = false
  vm_id               = 104
  agent {
    enabled = true
    timeout = "15m"
    trim    = false
    type    = "virtio"
  }
  cpu {
    architecture = ""
    cores        = 4
    flags        = []
    hotplugged   = 0
    limit        = 0
    numa         = false
    sockets      = 1
    type         = "x86-64-v2-AES"
  }
  disk {
    aio               = "io_uring"
    backup            = true
    cache             = "none"
    datastore_id      = "local-lvm"
    discard           = "ignore"
    file_format       = "raw"
    file_id           = ""
    import_from       = ""
    interface         = "scsi0"
    iothread          = true
    path_in_datastore = "vm-104-disk-0"
    queues            = 0
    replicate         = true
    serial            = ""
    size              = 20
    ssd               = false
  }
  disk {
    aio               = "io_uring"
    backup            = false
    cache             = "none"
    datastore_id      = "archive-pool"
    discard           = "on"
    file_format       = "raw"
    file_id           = ""
    import_from       = ""
    interface         = "scsi1"
    iothread          = false
    path_in_datastore = "vm-104-disk-0"
    queues            = 0
    replicate         = true
    serial            = ""
    size              = 64
    ssd               = true
  }
  memory {
    dedicated      = 131072
    floating       = 0
    keep_hugepages = false
    shared         = 0
  }
  operating_system {
    type = "l26"
  }
}
