# The tailscale-gateway LXC (CTID 100, 192.168.50.102) -- the fifth guest, and
# the only one of the five in state today.
#
# Body generated by `tofu plan -generate-config-out` from the live container on
# 2026-09-04, then reviewed and trimmed by hand. Three edits were needed, all of
# them provider artifacts rather than facts about the machine:
#
#   - `entrypoint = ""` was emitted and then rejected by the provider's own
#     validator ("Disallow Invalid Characters"). Generation and validation
#     disagree; the attribute is optional, so it is simply gone.
#   - `timeout_* = null` was emitted for attributes that have schema defaults,
#     which produced a permanent "update in-place" diff. See the lifecycle
#     block below.
#   - `hook_script_file_id = ""`, `pool_id`/`vm_id = null`: empty values for
#     things that do not exist, dropped. `template_file_id = ""` looks
#     identical but CANNOT be dropped -- the schema marks it required, so
#     removing it fails with "Missing required argument". Kept, empty, on the
#     provider's insistence rather than because it means anything.
#
# Imported 2026-09-04: `1 to import, 0 to change, 0 to destroy`. The apply made
# no API write to Proxmox -- an import is a state write -- which is why it was
# safe to run on a running guest with a read-only token.
#
# Note the bind mount: /mnt/sas1/tailscale-gateway-logs on the host. That is a
# storage location outside archive-pool and outside local-lvm, and it is not
# documented anywhere else in this repo.

import {
  to = proxmox_virtual_environment_container.tailscale_gateway
  id = "pve/100" # 192.168.50.102 -- tailscale-gateway
}

resource "proxmox_virtual_environment_container" "tailscale_gateway" {
  description           = ""
  environment_variables = {}
  node_name             = "pve"
  protection            = false
  start_on_boot         = true
  started               = true
  tags                  = []
  template              = false
  unprivileged          = true
  console {
    enabled   = true
    tty_count = 2
    type      = "tty"
  }
  disk {
    acl           = false
    datastore_id  = "local-lvm"
    mount_options = []
    quota         = false
    replicate     = false
    size          = 8
  }
  features {
    fuse    = false
    keyctl  = false
    mknod   = false
    mount   = []
    nesting = true
  }
  initialization {
    hostname = "tailscale-gateway"
    ip_config {
      ipv4 {
        address = "192.168.50.102/24"
        gateway = "192.168.50.1"
      }
    }
  }
  memory {
    dedicated = 1024
    swap      = 1024
  }
  mount_point {
    acl           = false
    backup        = false
    mount_options = []
    path          = "/var/log/ts-ssh-records"
    quota         = false
    read_only     = false
    replicate     = true
    shared        = false
    size          = ""
    volume        = "/mnt/sas1/tailscale-gateway-logs"
  }
  network_interface {
    bridge       = "vmbr0"
    enabled      = true
    firewall     = false
    host_managed = false
    mac_address  = "BC:24:11:AA:7D:5A"
    mtu          = 0
    name         = "eth0"
    rate_limit   = 0
    vlan_id      = 0
  }
  # timeout_* describe THIS CLIENT's patience, not the container. Proxmox has no
  # such fields, so import reads them as null and the schema defaults re-add
  # them on every plan -- a permanent diff that no apply against the host could
  # ever settle. Ignoring them is what makes "the plan must be clean" a rule
  # that can actually be enforced here.
  lifecycle {
    prevent_destroy = true

    ignore_changes = [
      timeout_clone,
      timeout_create,
      timeout_delete,
      timeout_start,
      timeout_update,
    ]
  }

  operating_system {
    template_file_id = ""
    type             = "ubuntu"
  }
}
