apiVersion: v1
kind: Secret
metadata:
    name: offsite-backup
    namespace: sunfire
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:s/MPvStitxUeer987dYdyWYQBfJr94OGu/cGfQRl8nnSzzxEh30vbT/+i0G/AAbIOVpxRz3pfq3npZsWaV2OZImyqHIobBjDE+M=,iv:hvgUKZqJUBgBXOV44d4ovpimP0cZBiaVaJH+1QkY8rc=,tag:bifISrM9Zs8aBPNijIDHNw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:JKNtYi+eSE51BwkkjZcP/fdXdtyrT74t1V9mebqPrbcBG8+blBoZm73TQFKMtNTb4NJs8X6FMQG9YH7dwEsNjA==,iv:5hkehD6aek/85DGY0k2NFRGJkrc0Vgs/Bt8y8Un+hnY=,tag:NtP5nY76eGcumtD2ohsXjQ==,type:str]
    B2_KEY_ID: ENC[AES256_GCM,data:I3HnlQShY0tc8ommVaLl8mbt9Q+ET9AXZg==,iv:+Hh5DIR1A5kxGzrKcBT89iNehzG1z31N9oxz36fbo7I=,tag:6QwMdVNV6Tk7Zm63Zvv0Cg==,type:str]
    B2_APP_KEY: ENC[AES256_GCM,data:rugWolO3calvR8pH+YcNmp26EkJ7VgB7cRrDg9FW2w==,iv:TxNSXMMsyJTci9o09AbMjXe6XrDJx+M/C43AvZOqGBk=,tag:aeAtXj3+j30NTFZ45nw3zw==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:fY707G8ZXTO2nUcdhA0Agn+dDGI=,iv:OGBusDRNFLI0X5DSV0hIJSA+owuyBSZMQBmdK4IdbWs=,tag:FPDad/YBcVKXRYjkCrIb8w==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:imUQ5tpWxJsnni7/GDNSR65kWGMFpXv2cdXM9T0ZfVTvIbcXcGrOmg==,iv:hKrPKRTxnjWQp+AERdvQp4OgP8y0oh84WIYd8vHPfnU=,tag:RwAaKmWz1fmJi19awymkPA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBScEZaMjF1VGlLdFNpRlpV
            dk0zdTduenRtNHZ5aDhIcG5EdnNCVHpTL2hVCklxcGN4WmN4cjVZZG1FUGRQdktJ
            VVB5L1d4RDZEbElsOE9SMG5HekdCRkEKLS0tIE5wcXRJQ2tCNXNXMHVsczl1OTRr
            MDVQUVp5Y3p2UFZmRE0rZmFvNVVteFEKF3s7H661WMjavGcD9gBlvIOHxDXMmUea
            tsXNM9VidFfQ/woqEZBKAUJ4GZ4uzH5fOnedBtUaPVnPc5i6F9mQxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ncpf5hg778lpszpv0u9mm48k5sdlm4y4v4dfsnaqskuwtwfgn3eqkz25qt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T18:03:36Z"
    mac: ENC[AES256_GCM,data:P66fUV66Vtq5Lq0jileQeHT94j9YQAR7QLgI9MCWLw6I383uicnrYB/AHAoXte+npUKz75L+G1XKjhsRdMHZUMSIKzBXFToAr2U8R2ZOw/JnjuJr9t4s5CJOgxyQR/DEDwiRHnHC7YyQTqTrVjrBrWGNOiGbfRVLONYugBzkAe4=,iv:A6z7+UutW3JhrKXgTMHU5pqUk+17Ny58htAlHR9z0dg=,tag:6iBf5YPZlhWi43ErnNuCYg==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
