apiVersion: v1
kind: Secret
metadata:
    name: postgres-authenticator
    namespace: sunfire
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:EjHwCTqMeJDlphy6Jw==,iv:xfRtaAl+XuyrUjMMXow1gzf4IeNGPBfYI6pZezXQXmg=,tag:N2Kt4l4oUsUHd6SiDDnVew==,type:str]
    password: ENC[AES256_GCM,data:12hUTGVeUMOC9J/NYN86VBDtWeXBBNvpSW0MnoB1xRzwLX7d9UgPHeYsjDcPCZOR,iv:xX9X5VOPEYxuJy56gQnnpG6Fqmut2JaLOwDU6qiK25w=,tag:BukN9lsuuZtqSMkPqTJy6Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUUVia1cwUFFXKytQbnds
            OUJQdlUycC83NFMyUWdiM2MrakgraFNmREdFCll1SGp0OEMyY0s2VjQ4SWloTXUw
            TU9iMExIUi96L3FITDFmdU5KMCtqS3cKLS0tIE45dy9RRWc4a294OHNjQjF3NzJR
            a1JGKzROL3B5TXFreHdVRmFrNytUMmcKGWmUBXcGMIaep6Tl4zmevqg9j9adaiIO
            Pc90h4LaXPgvbuhWk6XaSJwTumOj80+GN/1l0kAJkgqjm1mrx129Wg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ncpf5hg778lpszpv0u9mm48k5sdlm4y4v4dfsnaqskuwtwfgn3eqkz25qt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-03T19:17:38Z"
    mac: ENC[AES256_GCM,data:xHapSJIGfR7eXtAmAwkFOPA3Kq6TcoxOrVBy6aW00zuSBFXeTwct4G5D1jXjw8hsNTwG8ARNc5U1Zs9RCnM/YNcmX4zKQ6eaUzfBEFp1NLM8CLh3FVpSUPnkc5UTe3pZTzTKKwyZjvVPBWENscMkAnRjgNB4iQGrDWuNwQgtY60=,iv:IQ/3hIrSBAohtCIPTb04oi+E0XYVWx3mWi0YJ8HtoWI=,tag:uv6WurvSTw6XqY7E3Jf2rg==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
