apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authenticator-secret.sops.yaml
  - objectstore-secret.sops.yaml
  - objectstore.yaml
  - cluster.yaml
  - scheduledbackup.yaml
