apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-s3
    namespace: sunfire
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:UJ/bHY3BRPNLE4kzJlmmtGn3UfQ=,iv:zPwQDs1qHRcJrAjPmlQ7IPRjjvOkbLY6HOC0CWOGqTM=,tag:zDVmHb6sDyiN7FepSo9ZUg==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:/D/KJtjyof0ag39B2xMYLiS+oObxR3rNYTpo+gpdbEkGkJyBxy94ew==,iv:tlTMJEoSijM1lHcnLOMjEqNhZhxCdLABxEYPfabTYfE=,tag:/8u6NdnW9L5lQgUkb8YY0A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSjVUVmRza2FuVldyOGFy
            VXNOS2pzMmhiQXpsTktoVHdnT3gxeGZVT0h3CnhDbDJxNGJSSFRvbXhHVmV5TWFK
            OFE5TFZMSnpSbVJqYS9UcVNJOU9nQW8KLS0tIHZzaXZ5THEreG9MdmVGTWRnMHVP
            L01MVS9VOUJNZmJka2MrdjhUbTRhekkKinC5jpgOSkQR7KW1/eQykMAWRcOKCZD7
            N3r+I8DahUloA4IHZ5oN26Q1kYbTSR1MPSUWxF4EGVpMg/R8jrs/Ng==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ncpf5hg778lpszpv0u9mm48k5sdlm4y4v4dfsnaqskuwtwfgn3eqkz25qt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-04T00:48:27Z"
    mac: ENC[AES256_GCM,data:tY3+D2coTzqC9Age2nehkK+ITc8+N0ajyLSXMQ3U9qZmL0X4Ek8qYmATM9/OBsyyUQr+06m7LiQ03QPcSu/BoSvf9M0pAgYAWCvqkTPPefK6D+5XGH8YrF80DJrz7G4XhyUP4wu6gLvABpPSAbqndzO2ivXgFApDa+8G7ip2gF0=,iv:RSlgxNcvMpK/SNOGzzpZqgUol34IL8+MOBcFTBhKrSI=,tag:eDNthIbpFdq/yLzZ81WcSQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
