apiVersion: v1
kind: Secret
metadata:
    name: minio-credentials
    namespace: sunfire
type: Opaque
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:U7h2MbXgD7FuH6l/Lw==,iv:FKCNXhrqaMUBgSu9SgGWlbcaM46lUuvH8O7n5B5yyNo=,tag:UnBaBeifcqhCZwpCHFTC2A==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:9QPNY2VCriz4gnacWmOgTaAMMg3gm/6cwnoV2ZmBCJXk3PxhTPPkDS483y8LGM/0,iv:PFWooBaPazB8lRYjXAKrfDLJ8f3S96FwDn2iJvFOSdc=,tag:gFIVpEyG+5g419c4uxdJ/Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TkE1Z0ExMktoMHpIcjdU
            eThzWHBXQ2ZRTUVlUjZkbUprcnAva1MzbDM0CmhvNkN2RTZuZk8wQm5rQzZKaGdj
            ZmpEV3REMnArT0tYdFNaTWswd3BnWU0KLS0tIE8yUjZWU2JrYzR1UzJqa3BCdFpI
            dTRtYkhYQkZiem1TSHVXc0dYOHU3Q3cKEGwBOh2Ea3g0633DH2iGpBoUL+PjQoqQ
            koL78NiJOOMZatpaA72kRFwkMqFrVhgzuM+rewlyVoIxG1vl5yDJxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ncpf5hg778lpszpv0u9mm48k5sdlm4y4v4dfsnaqskuwtwfgn3eqkz25qt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-02T22:11:15Z"
    mac: ENC[AES256_GCM,data:jkn6QeqKtX7eVWWlP4il2KYWWNGEv1fqLYQgduIEQ+tQ0XB+uPsuDzMeTggOyP2Hsq4fiLbXHGQu+3igeedd0rnwuxFcABke8o2qQyVhkJt225dN2Dq2LsQ9Ff0luU9wTG8HYgANLA518eNmjsM/6KMRtgqVoYOKGndL9TKASQk=,iv:qyH9ntxmUhF5OtTNFCxP1i4RZIfZguowrOBzL+1DkNw=,tag:cyyCNctUascgl6acOPDp1Q==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
