apiVersion: v1
kind: Secret
metadata:
    name: minio-worker-credentials
    namespace: sunfire
type: Opaque
stringData:
    #ENC[AES256_GCM,data:9dWwQAM4rLgHQP3aCzqngcnK/TJUGw8WPozirbLAbi3II1snBaAwYvNRzNTd1vlJLoUXUaSSOJb49lOU5esNFwJ//cPjqg==,iv:5GigzqiJEtltiknwb/K0oMxhDQmcLwW5uxtJHJ6TShc=,tag:n03Bf3+qdKxYkuAX+kHGxw==,type:comment]
    PROD_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:9XEN2Zfj46nveu5Uh53KvS2AhCQ=,iv:zqe1hJnuvRI/vSLqlUSkNgs9xOOUhwJyS8xHtoUwX9Y=,tag:s7IIyvv4y6FKEpljufFltw==,type:str]
    PROD_MINIO_SECRET_KEY: ENC[AES256_GCM,data:xXHZ3gKQ55Rt/VqAQBoDwjHFf8m7/2//8uTEhwBk7tJ9hXfM/zBwPA==,iv:SjU4tGmd/CW67vrteJl2xurgdlrs7KVuwgEu/FUo0OY=,tag:gKbpTvVjA+nIrN+/wbo2NQ==,type:str]
    #ENC[AES256_GCM,data:ZECg8ogEttAMpEn+/KwZ8XdP6QcLUtwLvG1QxvgJet5nBscb+mOwjjhXlHAcOnK1HQOCpYFF4PgKLCD2uN9ZrD2ZECnubnjZBKdYa/azeGyn6z32EAsC,iv:EeYUVUMspsFyTuVs/vhvLDVfgxlmv61uVFfzNpxX+80=,tag:w7oV9MZgv8t/SkNnSK/1Vg==,type:comment]
    FEATURE_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:s0oKxA0Y74Kq2iUBb6bFtuPdI/M=,iv:vDbGN2Eelhav8qpyU/o5sAk4ggs7Sgh4xGbH+S7VlTI=,tag:5u918l7/RSAIRoCqvqlmHQ==,type:str]
    FEATURE_MINIO_SECRET_KEY: ENC[AES256_GCM,data:SvofMZWONx1O3CxRhoal/12XUjxYiSq1Xvu/DhUC3YWoi2O0SsHTsQ==,iv:nzRGcrv03K/yJgcNZ41hd28zo5Ho1Is/ihsoxnvicm4=,tag:leGwyhdGhyQNnoNunUEUtg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZEp3UktWZzBWVENYeTZj
            R1FkNXI4bEdGNUhpYk1mZmhMQ0VVNDMrUVhRCmRWSUlnVExBR3dNeDZWNWIvQjF2
            VWlEbVF2Rml1d0RvUXRpVjExbCtJVUEKLS0tIGcwQjR3TUdYMy90amlqR2JUNmt2
            MGNieTArQUVzdEZXOHdaTkJjQWVLUXMKC7+slztzyIv7xdcM+goYLW33bwnrVyAJ
            W71vSaFu0PafKWSkfBoJL2i+CIdEyQGbfWfbUvupuXW5VeqjJallAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ncpf5hg778lpszpv0u9mm48k5sdlm4y4v4dfsnaqskuwtwfgn3eqkz25qt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-02T22:11:15Z"
    mac: ENC[AES256_GCM,data:xV+q+PU41olSeBSSsWzzgm6ZSedBHPr7wUbXHM3C3oillnjc6sSLxUpfn2LoA4a5feTHqq0s2ui2wX9CwIXTpyfWsNGKoHf9VRgztbsiOHrpwE30LIb5Ltpn6D0qmoMOws4QYkpzuGbEPw35tJ8+MQQdZ9bXTjk+ddQ8EoYszX4=,iv:KV/NAxfZZxt/OvLxvqUnvGwVxBNgg79N2mbGE/hCYLU=,tag:+94vYCY9d68riQjPvOXOPQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
