wifi_ssid: ENC[AES256_GCM,data:OT03wTZP+hmC,iv:AbQPkTqen9MY+F0IpMzBa1R2wB0MmWeQ0vQNJbfs40E=,tag:svLoe3vVcEkCPLzkq05tXg==,type:str]
wifi_password: ENC[AES256_GCM,data:1JjC9Wo3ZEsT2k1j9KTH,iv:6g//lxlKkBDE5/GwAm5kr8qS3gdMFyoptF7iw8taYzI=,tag:bfrhFqtFbudGgL71Pnnp0Q==,type:str]
api_encryption_key: ENC[AES256_GCM,data:su4dNQDz2KUitPaH1b3KHI0gaKGqakHmKwB334dR4yW64eZiWZJbTVBVq7w=,iv:K4cdP/AxyXg2puxPNksnPyFvkm8AqPzSACsUCdE+v14=,tag:yitIqz30eWZVyjuFZFfRyA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RXZaQS9SWW5CaHFWQ2Q1
            bWFOd3FLSEZnRmJ2NG45REhrU1A3M0Foc0JzClNJRFo0RGRFaHdwbmcyaHY2cTEw
            UHA0alJtOVBuamp6N1UxVkJUQkNaRlEKLS0tIDdWMkR6Z081YjJFU1JIQmtCNUtn
            WUp6amZTbUNqQS9DMHlNNXliWmk2SUEKCUX4wEKN/63JFvr5QNXir8GkDjlLYXbn
            Cc4XKCcVZM45GhjHW9zLS+Ja7C2XurcoUeFzCA8ZIxox3+rXcxvNYQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ncpf5hg778lpszpv0u9mm48k5sdlm4y4v4dfsnaqskuwtwfgn3eqkz25qt
    lastmodified: "2026-09-19T05:49:12Z"
    mac: ENC[AES256_GCM,data:Hmu0dEpF7mKsasvqIiSPl56rQSLuXmVT8OKi9ATOoOxA+UQx2Qz8FFlhiQfnwpFNdghGPn42SVX2/bnNNRIKNXaQLW62wd2C04OC3f5qAOlPdN6HmIF96iF/zh76THHGHR4n8aWm5nVPn5mpGBvCTzAl4V/YSLYhuJZG075I0pc=,iv:6/TgcsrYVsPZCzMkPkxUsL9Pg3hijQyeGMnBDIwa60M=,tag:aNhEH51jO8XfxNAvTKxp5g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
