wifi_ssid: ENC[AES256_GCM,data:OT03wTZP+hmC,iv:AbQPkTqen9MY+F0IpMzBa1R2wB0MmWeQ0vQNJbfs40E=,tag:svLoe3vVcEkCPLzkq05tXg==,type:str]
wifi_password: ENC[AES256_GCM,data:nxkGOWhH31JH/ZRRs+d2fvY=,iv:wT/ffX+fOX8QJB5yXExKZLzlBTL6SFRWLRfrgyunGkE=,tag:oL9caV4Zlh/yRtuwKFYVtw==,type:str]
api_encryption_key: ENC[AES256_GCM,data:su4dNQDz2KUitPaH1b3KHI0gaKGqakHmKwB334dR4yW64eZiWZJbTVBVq7w=,iv:K4cdP/AxyXg2puxPNksnPyFvkm8AqPzSACsUCdE+v14=,tag:yitIqz30eWZVyjuFZFfRyA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RXZaQS9SWW5CaHFWQ2Q1
            bWFOd3FLSEZnRmJ2NG45REhrU1A3M0Foc0JzClNJRFo0RGRFaHdwbmcyaHY2cTEw
            UHA0alJtOVBuamp6N1UxVkJUQkNaRlEKLS0tIDdWMkR6Z081YjJFU1JIQmtCNUtn
            WUp6amZTbUNqQS9DMHlNNXliWmk2SUEKCUX4wEKN/63JFvr5QNXir8GkDjlLYXbn
            Cc4XKCcVZM45GhjHW9zLS+Ja7C2XurcoUeFzCA8ZIxox3+rXcxvNYQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ncpf5hg778lpszpv0u9mm48k5sdlm4y4v4dfsnaqskuwtwfgn3eqkz25qt
    lastmodified: "2026-09-17T04:20:59Z"
    mac: ENC[AES256_GCM,data:FRVjuuN3360knGt7I30G2REWTdSMFcRWzU2pZyM51EsQ7Bz9rhor7oH/UHk4xqxDuihx7mH/Mm/gZBlOkF23772ggLEUQgyNlztUUG0XLbVdrI5XIgOUqhfFzhaOixUKLwBILtZxYpezQ6xrCmjxMmWRufbt5kbGNaAKKPl8KME=,iv:yiWMpG5bHQmBQ9+Cjl8US+8SPc1WmD0Swm9eopkifH8=,tag:TYiipSqR6pcnhHKjZYv6eA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
